--24520549 --Ngô Xuân Minh Hoàng

--TAO DATABASE
CREATE DATABASE QuanLyHangHoa
GO
USE QuanLyHangHoa

--NHAP DU LIEU
CREATE TABLE NHACUNGCAP
(
	MANCC VARCHAR(5) PRIMARY KEY,
	TENNCC VARCHAR(20) NULL,
	TRANGTHAI NUMERIC(2,0) NULL,
	THANHPHO VARCHAR(30) NULL
)
GO


CREATE TABLE PHUTUNG
(
	MAPT VARCHAR(5) PRIMARY KEY,
	TENPT VARCHAR(10),
	MAUSAC VARCHAR(10),
	KHOILUONG FLOAT,
	THANHPHO VARCHAR(10)
)
GO


CREATE TABLE VANCHUYEN
(
	MANCC VARCHAR(5) FOREIGN KEY REFERENCES NHACUNGCAP(MANCC),
	MAPT VARCHAR(5) FOREIGN KEY REFERENCES PHUTUNG(MAPT),
	SOLUONG NUMERIC(5,0),
	CONSTRAINT PK_VANCHUYEN PRIMARY KEY(MANCC,MAPT)
)
GO

--NHAP DU LIEU VO BANG

INSERT INTO NHACUNGCAP (MANCC,TENNCC,TRANGTHAI,THANHPHO) 
VALUES 
('NCC01', 'Phu Tung Viet', 1, 'Ha Noi'),
('NCC02', 'Auto Parts Co', 0, 'Hai Phong'),
('NCC03', 'Cty Dong Luc', 1, 'Da Nang'),
('NCC04', 'Spares Ltd',   0, 'TpHCM'),
('NCC05', 'Mech Co',      0, 'Can Tho')
GO

INSERT INTO PHUTUNG (MAPT, TENPT, MAUSAC, KHOILUONG, THANHPHO)
VALUES
('PT01', 'Bulong',   'Do',    0.5, 'Ha Noi'),
('PT02', 'OcVit',    'Xanh',  0.2, 'Hai Phong'),
('PT03', 'DayCuRoa', 'Den',   1.5, 'Da Nang'),
('PT04', 'BanhRang', 'Trang', 2.0, 'TpHCM'),
('PT05', 'VoXe',     'Den',   3.2, 'Can Tho')
GO

INSERT INTO VANCHUYEN (MANCC, MAPT, SOLUONG)
VALUES
('NCC01', 'PT01', 100),
('NCC01', 'PT02', 200),
('NCC02', 'PT03', 150),
('NCC03', 'PT04', 300),
('NCC04', 'PT05', 250)
GO