--24520549 --Ngô Xuân Minh Hoàng

USE QuanLyBanHang
GO

--I.2
ALTER TABLE SANPHAM ADD GHICHU VARCHAR(20)
GO

--I.3
ALTER TABLE KHACHHANG ADD LOAIKH TINYINT
GO

--I.4
ALTER TABLE SANPHAM ALTER COLUMN GHICHU VARCHAR(100)
GO

--I.5
ALTER TABLE SANPHAM DROP COLUMN GHICHU
GO

--I.6
ALTER TABLE KHACHHANG ALTER COLUMN LOAIKH VARCHAR(20)
GO

--I.7
ALTER TABLE SANPHAM ADD CONSTRAINT RBTV_DVT CHECK(DVT IN ('cay','hop','cai','quyen','chuc'))
GO

--I.8
ALTER TABLE SANPHAM ADD CONSTRAINT RBTV_GIA CHECK (GIA >= 500)
GO

--I.9
ALTER TABLE CTHD ADD CONSTRAINT RBTV_SL CHECK(SL > 0)
GO

--I.10
ALTER TABLE KHACHHANG ADD CONSTRAINT RBTV_NGDK CHECK(NGDK > NGSINH)

--II.2
SELECT * INTO SANPHAM1 FROM SANPHAM
SELECT * INTO KHACHHANG1 FROM KHACHHANG
GO

--II.3
UPDATE SANPHAM1
SET GIA = GIA * 1.05
WHERE NUOCSX = 'Thai Lan'
GO

--II.4
UPDATE SANPHAM1
SET GIA = GIA * 0.95
WHERE NUOCSX = 'Trung Quoc' AND GIA <= 10000
GO

--III.1
SELECT MASP,TENSP 
FROM SANPHAM
WHERE NUOCSX = 'Trung Quoc'
GO

--III.2
SELECT MASP,TENSP
FROM SANPHAM
WHERE DVT IN ('cay','quyen')
GO

--III.3
SELECT MASP,TENSP
FROM SANPHAM
WHERE MASP LIKE 'B%01'
GO

--III.4
SELECT MASP,TENSP
FROM SANPHAM
WHERE NUOCSX = 'Trung Quoc' AND GIA >= 30000 AND GIA <= 40000
GO

--III.5
SELECT MASP,TENSP
FROM SANPHAM 
WHERE (NUOCSX = 'Trung Quoc' OR NUOCSX = 'Thai Lan') AND GIA >= 30000 AND GIA <= 40000

--III.6
SELECT SOHD,TRIGIA 
FROM HOADON
WHERE NGAYHD = '2007-01-01' OR NGAYHD = '2007-01-02'

--III.7
SELECT SOHD,TRIGIA
FROM HOADON
WHERE MONTH(NGAYHD) = 1 AND YEAR(NGAYHD) = 2007
ORDER BY NGAYHD ASC, TRIGIA DESC