--24520549 --Ngô Xuân Minh Hoàng

USE QuanLyGiaoVu
GO

--I.3
ALTER TABLE HOCVIEN ADD CONSTRAINT RBTV_GIOITINH CHECK(GIOITINH IN ('Nam','Nu'))
ALTER TABLE GIAOVIEN ADD CONSTRAINT RBTV_GIOITINH CHECK(GIOITINH IN ('Nam','Nu'))
GO

--I.4
ALTER TABLE KETQUATHI ADD CONSTRAINT RBTV_DIEM CHECK(DIEM >=0 AND DIEM <= 10)
GO

--I.5
ALTER TABLE KETQUATHI ADD CONSTRAINT RBTV_KQUA CHECK((KQUA = 'Dat' AND DIEM >= 5 AND DIEM <= 10) OR (KQUA = 'Khong dat' AND DIEM >= 0 AND DIEM < 5))
GO

--I.6
ALTER TABLE KETQUATHI ADD CONSTRAINT RBTV_LANTHI CHECK(LANTHI >=0 AND LANTHI <=3)
GO

--I.7
ALTER TABLE GIANGDAY ADD CONSTRAINT RBTV_HOCKY CHECK(HOCKY >= 1 AND HOCKY <= 3)
GO

--I.8
ALTER TABLE GIAOVIEN ADD CONSTRAINT RBTV_HOCVI CHECK(HOCVI IN ('CN','KS','Ths','TS','PTS'))
GO

--I.9
ALTER TABLE LOP ADD CONSTRAINT RBTV_TRGLOP CHECK(MALOP(TRGLOP) = MALOP)
GO

--I.10
ALTER TABLE KHOA ADD CONSTRAINT RBTV_TRGkHOA CHECK(MAKHOA(TRGkHOA) = MAKHOA AND HOCVI(TRGKHOA) IN ('TS','PTS'))
GO

--I.11
ALTER TABLE HOCVIEN ADD CONSTRAINT RBTV_TUOI CHECK((YEAR(GETDATE()) - YEAR(NGSINH)) >= 18)
GO

--I.12
ALTER TABLE GIANGDAY ADD CONSTRAINT RBTV_TUNGAY_DENNGAY CHECK (TUNGAY < DENNGAY)
GO

--I.13
ALTER TABLE GIAOVIEN ADD CONSTRAINT RBTV_NGVL CHECK((YEAR(NGVL) - YEAR(NGSINH)) >= 18)
GO

--I.14
ALTER TABLE MONHOC ADD CONSTRAINT RBTV_TC CHECK(ABS(TCLT - TCTH) <= 3)
GO

--III.1
SELECT MAHV,(HO + ' ' +TEN) AS HOTEN,NGSINH,HOCVIEN.MALOP FROM LOP INNER JOIN HOCVIEN ON MAHV = LOP.TRGLOP
GO

--III.2
SELECT HOCVIEN.MAHV,(HOCVIEN.HO + ' ' + HOCVIEN.TEN) AS HOTEN ,LANTHI,DIEM 
FROM KETQUATHI INNER JOIN HOCVIEN ON HOCVIEN.MAHV = KETQUATHI.MAHV
WHERE MAMH = 'CTRR' AND HOCVIEN.MALOP = 'K12'
ORDER BY HOCVIEN.TEN DESC, HOCVIEN.HO DESC
GO

--III.3
SELECT HOCVIEN.MAHV,HOCVIEN.HO,HOCVIEN.TEN,MAMH
FROM HOCVIEN INNER JOIN KETQUATHI ON HOCVIEN.MAHV = KETQUATHI.MAHV
WHERE LANTHI = 1 AND DIEM >= 5
GO